apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
## ClusterRole -- ClusterRoleBinding -- ServiceAccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: default # Pod에 ServiceAccount가 설정되지 않은 경우, default ServiceAccount를 지정
    namespace: monitoring
